
class Common:
    chrome_path = "C:\DRIVERS\chromedriver.exe"
    edge_path = "C:\DRIVERS\msedgedriver.exe"
    firefox_path = "C:\DRIVERS\geckodriver.exe"
    resume_path = "C:\\Users\\JannGeo\\Downloads\\Resume.txt"
    download_url = "https://file-examples.com/index.php/sample-documents-download/sample-doc-download/"
    prd_dwnld_url = "https://file-examples.com/index.php/sample-documents-download/sample-pdf-download/"
    mime_types = "https://www.sitepoint.com/mime-types-complete-list/"
    monster = "https://www.foundit.com.ph/"
    dummy_ticket = "https://www.dummyticket.com/dummy-ticket-for-visa-application/"
    demo_nopcommerce = "https://demo.nopcommerce.com/"
    open_cart = "https://www.opencart.com/"
    orange_hrm = "https://www.orangehrm.com/"
    google = "https://google.com"
